
function(FIND_GSTRTSPSERVER)

#    message("=========================VCPKG_INSTALLED_DIR: " ${VCPKG_INSTALLED_DIR})
    if(UNIX)
        file(GLOB_RECURSE GSTRTSPSERVER_LIBS_DIR ${VCPKG_INSTALLED_DIR}/*/libgstrtspserver-?.?.a)
    elseif(WIN32)
        file(GLOB_RECURSE GSTRTSPSERVER_LIBS_DIR ${VCPKG_INSTALLED_DIR}/*/gstrtspserver*.lib)
    endif()
    message("=========================GSTRTSPSERVER_LIBS_DIR: " ${GSTRTSPSERVER_LIBS_DIR})
    list(GET GSTRTSPSERVER_LIBS_DIR -1 GSTRTSPSERVER_LIBS_DIR)
    cmake_path(GET GSTRTSPSERVER_LIBS_DIR PARENT_PATH GSTRTSPSERVER_LIBS_DIR)
    set(GSTRTSPSERVER_LIBS_DIR ${GSTRTSPSERVER_LIBS_DIR} PARENT_SCOPE)

    file(GLOB_RECURSE GSTRTSPSERVER_INCLUDE_DIR ${VCPKG_INSTALLED_DIR}/*/gst.h NO_CACHE)
    list(GET GSTRTSPSERVER_INCLUDE_DIR -1 GSTRTSPSERVER_INCLUDE_DIR)
    cmake_path(GET GSTRTSPSERVER_INCLUDE_DIR PARENT_PATH GSTRTSPSERVER_INCLUDE_DIR)
    cmake_path(GET GSTRTSPSERVER_INCLUDE_DIR PARENT_PATH GSTRTSPSERVER_INCLUDE_DIR)
    #message("=========================GSTRTSPSERVER_INCLUDE_DIR: " ${GSTRTSPSERVER_INCLUDE_DIR})
    list(APPEND GSTRTSPSERVER_INCLUDE_DIR ${GSTRTSPSERVER_INCLUDE_DIR})

endfunction()

FIND_GSTRTSPSERVER()

add_library(GstRtspServer STATIC IMPORTED)

target_link_libraries(GstRtspServer
    INTERFACE ${GSTRTSPSERVER_LIBS_DIR}/libgstrtspserver-1.0.a
    INTERFACE z
)

set_property(TARGET GstRtspServer
    PROPERTY IMPORTED_LOCATION ${GSTRTSPSERVER_LIBS_DIR}/libgstrtspserver-1.0.a
)
