
function(FIND_GSTREAMER)

#    message("=========================VCPKG_INSTALLED_DIR: " ${VCPKG_INSTALLED_DIR})
    if(UNIX)
        file(GLOB_RECURSE GSTREAMER_LIBS_DIR ${VCPKG_INSTALLED_DIR}/*/libgstbase-?.?.a)
    elseif(WIN32)
        file(GLOB_RECURSE GSTREAMER_LIBS_DIR ${VCPKG_INSTALLED_DIR}/*/gstbase*.lib)
    endif()
 #   message("=========================GSTREAMER_LIBS_DIR: " ${GSTREAMER_LIBS_DIR})
    list(GET GSTREAMER_LIBS_DIR -1 GSTREAMER_LIBS_DIR)
    cmake_path(GET GSTREAMER_LIBS_DIR PARENT_PATH GSTREAMER_LIBS_DIR)
    set(GSTREAMER_LIBS_DIR ${GSTREAMER_LIBS_DIR} PARENT_SCOPE)

    file(GLOB_RECURSE GSTREAMER_INCLUDE_DIR ${VCPKG_INSTALLED_DIR}/*/gst.h NO_CACHE)
    list(GET GSTREAMER_INCLUDE_DIR -1 GSTREAMER_INCLUDE_DIR)
    cmake_path(GET GSTREAMER_INCLUDE_DIR PARENT_PATH GSTREAMER_INCLUDE_DIR)
    cmake_path(GET GSTREAMER_INCLUDE_DIR PARENT_PATH GSTREAMER_INCLUDE_DIR)
    #message("=========================GSTREAMER_INCLUDE_DIR: " ${GSTREAMER_INCLUDE_DIR})
    list(APPEND GSTREAMER_INCLUDE_DIRS ${GSTREAMER_INCLUDE_DIR})

    file(GLOB_RECURSE GLIB_INCLUDE_DIR ${VCPKG_INSTALLED_DIR}/*/glib.h NO_CACHE)
    list(GET GLIB_INCLUDE_DIR -1 GLIB_INCLUDE_DIR)
    cmake_path(GET GLIB_INCLUDE_DIR PARENT_PATH GLIB_INCLUDE_DIR)
    #message("=========================GLIB_INCLUDE_DIR: " ${GLIB_INCLUDE_DIR})

    list(APPEND GSTREAMER_INCLUDE_DIRS ${GLIB_INCLUDE_DIR})

    file(GLOB_RECURSE GLIB_INCLUDE_DIR2 ${VCPKG_INSTALLED_DIR}/*/glibconfig.h )
    list(GET GLIB_INCLUDE_DIR2 -1 GLIB_INCLUDE_DIR2)
    cmake_path(GET GLIB_INCLUDE_DIR2 PARENT_PATH GLIB_INCLUDE_DIR2 )
    #message("=========================GLIB_INCLUDE_DIR2: " ${GLIB_INCLUDE_DIR2})

    list(APPEND GSTREAMER_INCLUDE_DIRS ${GLIB_INCLUDE_DIR2})
    set(GSTREAMER_INCLUDE_DIRS ${GSTREAMER_INCLUDE_DIRS} PARENT_SCOPE)

    #message("===========> !GSTREAMER_INCLUDE_DIRS: " ${GSTREAMER_INCLUDE_DIRS})

    file(GLOB_RECURSE GLIB_LIBS_DIR ${VCPKG_INSTALLED_DIR}/*/libglib-?.?.a )
    list(GET GLIB_LIBS_DIR -1 GLIB_LIBS_DIR)
    cmake_path(GET GLIB_LIBS_DIR PARENT_PATH GLIB_LIBS_DIR )
 #   message("===========> !GLIB_LIBS_DIR: " ${GLIB_LIBS_DIR})

    set(GLIB_LIBS_DIR ${GLIB_LIBS_DIR} PARENT_SCOPE)

endfunction()

FIND_GSTREAMER()

find_package(pcre2 REQUIRED)
find_package(libffi REQUIRED)

set(GSTREAMER_TARGET_NAME GStreamer)

add_library(${GSTREAMER_TARGET_NAME}::GStreamer STATIC IMPORTED)

target_link_libraries(${GSTREAMER_TARGET_NAME}::GStreamer 
    INTERFACE ${GLIB_LIBS_DIR}/libgobject-2.0.a
    INTERFACE ${GLIB_LIBS_DIR}/libgmodule-2.0.a
    INTERFACE ${GLIB_LIBS_DIR}/libglib-2.0.a
    INTERFACE libffi
    INTERFACE PCRE2::8BIT
    INTERFACE ${GSTREAMER_LIBS_DIR}/libgstreamer-1.0.a

    INTERFACE ${GSTREAMER_LIBS_DIR}/libgstapp-1.0.a
    INTERFACE ${GSTREAMER_LIBS_DIR}/libgstbase-1.0.a
)

target_include_directories(${GSTREAMER_TARGET_NAME}::GStreamer  INTERFACE
    ${GSTREAMER_INCLUDE_DIRS}
)

set_property(TARGET ${GSTREAMER_TARGET_NAME}::GStreamer
    PROPERTY IMPORTED_LOCATION ${GSTREAMER_LIBS_DIR}/libgstreamer-1.0.a
)
